### ISSUE TITLE
no sourcetable available

### ISSUE THREAD

**Issue by scientificcontributor1** [goblimey/ntripcaster#2]
Hi,
thanks a lot for this docker. It's awesome.
I still have a problem while running the image. After running:
curl http://localhost:2101
it answers:
SOURCETABLE 200 OK
Server: NTRIP NtripCaster 0.1.5/1.0
NO SOURCETABLE AVAILABLE
I kept your sourcetable.dat example and added my base station:
CAS;www.euref-ip.net;2101;EUREF-IP;BKG;0;DEU;50.12;8.69;http://www.euref-ip.net/home
CAS;rtcm-ntrip.org;2101;NtripInfoCaster;BKG;0;DEU;50.12;8.69;http://www.rtcm-ntrip.org/home
NET;EUREF;EUREF;B;N;http://www.epncb.oma.be/euref_IP;http://www.epncb.oma.be/euref_IP;http://igs.ifag.de/index_ntrip_reg.htm;none
NET;IGS;BKG;B;N;http://igscb.jpl.nasa.gov/;none;http://igs.ifag.de/index_ntrip_reg.htm;none
STR;DODO1;Saint-Leu;RTCM 3.0;;;;;REU;-21.16;55.29;1;0;sNTRIP;none;N;N;0;;

but it doesn't print when I curl it...
thanks a lot!
Sylvain

**Comment by nealf** [comment]
@scientificcontributor1 Any chance you figured this issue out at some point? I've just run into it myself! 😄

**Comment by nealf** [comment]
If anybody else happens to end up here, I was able to work around this issue by changing the relative reference to the `sourctable.dat` file to be absolute which worked. My C is too rusty and time too short to figure out why relative isn't working, so I just changed [this line](https://github.com/nunojpg/ntripcaster/blob/11846521e745d627a2d6c03c87b871eed63bce31/src/client.c#L381) in `src/client.c`:

```
// ifp = fopen("../conf/sourcetable.dat","r");
ifp = fopen("/usr/local/ntripcaster/conf/sourcetable.dat","r");
```

**Comment by charlesquick** [comment]
Wahay! thanks guys, I was looking at client.c for hours thinking 'this is all correct, why doesn't it work!?'
Also thanks to Goblimey for doing the containerisation work

**Comment by MichaelEFlip** [comment]
The origin of the problem seems to be the WORKDIR setting in the DOCKERFILE.
I created a pull request with a fix: https://github.com/goblimey/ntripcaster/pull/3

**Comment by goblimey** [comment]
Many apologies for my tardy response.  Apart from the pesky day job, I've been concentrating on my ntrip server, and I'm afraid I let this repository rot for a while. 

Yes, Michael is correct, the WORKDIR setting was wrong.  I've fixed it.

The original BKG documentation advises you to run the caster from /usr/local/ntripcaster.  In fact you should run it from the log directory within that.  When the caster starts up it creates its log file in the current directory and then the home page request handler assumes that it will find its source table in ../conf.  I guess that BKG's original intention was that it would create its log in ./log and fetch the source table from ./conf, but the demons of software development intervened.

There was also a mistake in my commands to copy the config files bfore you run the build :(

and new versions of curl need a small tweak to cope with the archaic style of the HTTP response.

Thank you also Michael for your pull request, which produces a smaller and more secure image. 

I'm in the process of reworking the README to clarify all this.

Regards

Simon

Chief developer (strictly the only developer (more strictly the only person)) at Goblimey
